"""changed pitch table to accomodate category and added category table

Revision ID: 525af16c32c7
Revises: cab0b8cfc783
Create Date: 2018-09-10 11:55:36.884743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525af16c32c7'
down_revision = 'cab0b8cfc783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
