"""added column Bio and profile_pic_path

Revision ID: 5418682d08b0
Revises: 039fcd9e76c7
Create Date: 2018-09-07 16:13:53.930678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5418682d08b0'
down_revision = '039fcd9e76c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
